# Site settings
title: The Story Hunt
url: https://storyhunt.de/

sass:
  ssas_dir: css/_sass
  style: compressed

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EEEEEE #d8b365
  primary-rgb: "39, 196, 244" #"216,179,101"
  secondary: 0A070C #B2230B
  secondary-dark: F62459 #01665e

# Build settings
markdown: kramdown
permalink: pretty

